#!/usr/bin/env bash
set -u

OUT="${1:-docs/LAB_README.md}"
SERVICE="${SERVICE:-cyber-agents-mlx}"
BASE_URL="${BASE_URL:-http://localhost:18110}"
OLLAMA_URL="${OLLAMA_URL:-http://localhost:11434}"
LOG_LINES="${LOG_LINES:-120}"
RUN_FULL="${RUN_FULL:-0}"
RUN_INGEST="${RUN_INGEST:-0}"

export BASE_URL OLLAMA_URL SERVICE LOG_LINES RUN_FULL RUN_INGEST

mkdir -p "$(dirname "$OUT")"

add_line() {
  printf '%s\n' "$1" >> "$OUT"
}

blank() {
  printf '\n' >> "$OUT"
}

heading() {
  blank
  add_line "## $1"
  blank
}

code_open() {
  add_line "\`\`\`$1"
}

code_close() {
  add_line "\`\`\`"
  blank
}

write_command_block() {
  local lang="$1"
  local body="$2"
  code_open "$lang"
  printf '%s\n' "$body" >> "$OUT"
  code_close
}

write_text() {
  printf '%s\n' "$1" >> "$OUT"
  blank
}

run_block() {
  local title="$1"
  local cmd="$2"
  local lang="${3:-text}"

  heading "$title"
  write_command_block "bash" "$cmd"
  code_open "$lang"
  bash -lc "$cmd" >> "$OUT" 2>&1
  local rc=$?
  blank
  add_line "exit_code=$rc"
  code_close
}

run_timed_post() {
  local title="$1"
  local endpoint="$2"
  local payload="$3"
  local cmd="/usr/bin/time -p curl -s ${BASE_URL}${endpoint} -H 'Content-Type: application/json' -d @${payload} | python3 -m json.tool"

  heading "$title"
  write_command_block "bash" "$cmd"
  code_open "text"
  /usr/bin/time -p bash -lc "curl -s '${BASE_URL}${endpoint}' -H 'Content-Type: application/json' -d @'${payload}' | python3 -m json.tool" >> "$OUT" 2>&1
  local rc=$?
  blank
  add_line "exit_code=$rc"
  code_close
}

# Start report. Do not use heredocs here; unquoted heredocs execute Markdown backticks.
: > "$OUT"
add_line "# Lab Environment Run Report"
blank
add_line "Generated by:"
blank
write_command_block "text" "scripts/lab_environment_check.sh"
add_line "Generated at:"
blank
write_command_block "text" "$(date)"
add_line "Base URLs:"
blank
write_command_block "text" "App:     ${BASE_URL}
Ollama:  ${OLLAMA_URL}
Service: ${SERVICE}"
write_text "This report captures the local Apple Silicon MLX cyber-agent lab environment, runtime status, timings, policy checks, triage output, audit status, and recent logs."

heading "Lab checklist summary"
write_text "Expected flow:

1. Confirm host, Git, Docker, and Ollama environment.
2. Confirm required MLX models are available.
3. Confirm policy source documents are present.
4. Build and start the Docker service.
5. Confirm the agent is running.
6. Confirm policy index and policy-family coverage.
7. Run policy search.
8. Run fast triage and capture timing.
9. Optionally run full deep triage and capture timing.
10. Capture audit status and recent container logs.
11. Save all output into this Markdown file."

run_block "Host system" "hostname; uname -a; sw_vers 2>/dev/null || true; sysctl -n machdep.cpu.brand_string 2>/dev/null || true"
run_block "Git state" "git branch --show-current 2>/dev/null || true; git rev-parse --short HEAD 2>/dev/null || true; git status --short 2>/dev/null || true"
run_block "Docker version" "docker --version; docker compose version"
run_block "Docker service status before start" "docker compose ps"
run_block "Ollama version and model list" "ollama --version 2>/dev/null || true; curl -s \"${OLLAMA_URL}/api/tags\" | python3 -m json.tool"
run_block "Required model presence" 'TAGS="$(curl -s "$OLLAMA_URL/api/tags")"; for m in gemma4:e2b-mlx gemma4:e4b-mlx embeddinggemma:300m-qat-q8_0; do if printf "%s" "$TAGS" | grep -q "\"name\"[[:space:]]*:[[:space:]]*\"$m\""; then echo "$m: OK"; else echo "$m: MISSING"; fi; done'
run_block "Environment file check with safe redaction" "if [ -f .env ]; then sed -E 's/(TOKEN|PASSWORD|SECRET|KEY)=.*/\\1=REDACTED/g' .env; else echo '.env missing'; fi"
run_block "Policy raw documents" "find policy_docs/raw -maxdepth 1 -type f -print | sort; ls -lh policy_docs/raw"
run_block "Build and start Docker service" "docker compose up -d --build"
run_block "Docker service status after start" "docker compose ps"
run_block "Policy document validation" "docker compose exec -T ${SERVICE} python scripts/check_policy_docs.py"

if [ "$RUN_INGEST" = "1" ]; then
  run_block "Policy index build" "./scripts/policy_embed_all.sh"
else
  heading "Policy index build"
  write_text "Skipped by default."
  write_text "To rebuild the policy vector index and include the output in this report, run:"
  write_command_block "bash" "RUN_INGEST=1 ./scripts/lab_environment_check.sh"
fi

run_block "Health check" "curl -s ${BASE_URL}/health | python3 -m json.tool"
run_block "Agent registry check" "curl -s ${BASE_URL}/agents | python3 -m json.tool"
run_block "Policy index status" "curl -s ${BASE_URL}/policy/status | python3 -m json.tool"
run_block "Audit status before triage" "curl -s ${BASE_URL}/audit/status | python3 -m json.tool"
run_block "Policy search test" "curl -s ${BASE_URL}/policy/search -H 'Content-Type: application/json' -d '{\"query\":\"failed SSH login with possible personal data and security monitoring under GDPR and EU AI Act\",\"top_k\":6}' | python3 -m json.tool"

run_timed_post "Fast triage timing and result" "/triage/fast" "examples/ssh_failed_login.json"

if [ "$RUN_FULL" = "1" ]; then
  run_timed_post "Full triage timing and result" "/triage" "examples/ssh_failed_login.json"
else
  heading "Full triage timing and result"
  write_text "Skipped by default."
  write_text "To include full deep-triage timing, run:"
  write_command_block "bash" "RUN_FULL=1 ./scripts/lab_environment_check.sh"
  write_text "To rebuild policy index and run full triage in one run:"
  write_command_block "bash" "RUN_INGEST=1 RUN_FULL=1 ./scripts/lab_environment_check.sh"
fi

run_block "Audit status after triage" "curl -s ${BASE_URL}/audit/status | python3 -m json.tool"
run_block "Recent audit files" "find audit_logs -maxdepth 1 -type f -name '*.json' -print | sort | tail -10"
run_block "Container logs tail" "docker compose logs --tail=${LOG_LINES} ${SERVICE}"

heading "How to watch the agent live"
write_text "Use this while another terminal runs triage:"
write_command_block "bash" "docker compose logs -f --tail=50 ${SERVICE}"
write_text "Expected full-triage progress markers:"
write_command_block "text" "triage_started
redaction_done
signal_scan_done
policy_search_done
fast_classifier_done
deep_analyst_started
audit_write_started
triage_complete"
write_text "Expected fast-triage progress markers:"
write_command_block "text" "triage_fast_started
redaction_done
signal_scan_done
policy_search_done
fast_classifier_done
audit_write_started
triage_fast_complete"

heading "Lab result interpretation"
write_text "The lab is considered healthy when:

- Docker service is running.
- Ollama is reachable from the Mac host.
- Required models are present.
- /health returns ollama_reachable: true.
- Policy index exists.
- Policy chunk count is greater than zero.
- Policy families include GDPR, EU AI Act, GPAI guidance, and internal policy.
- /triage/fast returns an audit_id.
- /audit/status shows audit records.
- Container logs show triage progress markers."

echo "Lab report written to: $OUT"
